Fix missing dev dependency causing Travis to fail
```
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at stringify (/home/travis/build/hbz/oerworldmap-ui/node_modules/babel-runtime/node_modules/core-js/library/fn/json/stringify.js:4:26)
    at compile (/home/travis/build/hbz/oerworldmap-ui/node_modules/babel-register/lib/node.js:105:42)
    at loader (/home/travis/build/hbz/oerworldmap-ui/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/hbz/oerworldmap-ui/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /home/travis/build/hbz/oerworldmap-ui/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/travis/build/hbz/oerworldmap-ui/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/home/travis/build/hbz/oerworldmap-ui/node_modules/mocha/lib/mocha.js:495:10)
    at Object.<anonymous> (/home/travis/build/hbz/oerworldmap-ui/node_modules/mocha/bin/_mocha:469:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```